name: Adhoc Prerelease

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: false

jobs:
  build:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: Build & Publish a Prerelease to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16.7
        uses: actions/setup-node@v2
        with:
          node-version: 16.7
          cache: "npm"

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        run: npm install

      - name: Modify package.json version
        run: node .github/version-script.js

      - name: Build
        run: npm run build
        working-directory: packages/wrangler

      - name: Check for errors
        run: npm run check

      - name: Publish Prerelease without a tag to NPM
        if: ${{ !github.event.inputs.tag }}
        run: npm publish
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/wrangler

      - name: Publish Prerelease with a tag to NPM
        if: ${{ github.event.inputs.tag }}
        run: npm publish --tag ${{ github.event.inputs.tag }}
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/wrangler
